# Generated by Django 3.2.18 on 2023-04-11 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
